
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.229
neo_version_range=[21,)
jei_version=19.21.0.247

loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=awesome_storage
mod_name=Awesome Storage
mod_license=MIT
mod_version=1.0.6
mod_group_id=com.gihub.edg_thexu
mod_authors=EDGtheXu
mod_description=A mod that adds a simple storage container system to the game.


systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=7890